In [249]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Adithya K S\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Adithya K S\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Adithya K S\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Adithya K S\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Adithya K S\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [250]:
import pandas as pd
from  sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [251]:
data=pd.read_csv(r'C:\deepalm\AICW\churn_analysis\Churn_Modelling.csv')

In [252]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [253]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [254]:
data.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [255]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [256]:
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [257]:
#label encoding
Label_Encoder_gender=LabelEncoder()
data['Gender']=Label_Encoder_gender.fit_transform(data['Gender'])

In [258]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_geography=OneHotEncoder()
geo_encoder=one_hot_encoder_geography.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [259]:
one_hot_encoder_geography.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [260]:
geo_df=pd.DataFrame(geo_encoder,columns=u.get_feature_names_out(['Geography']))

NameError: name 'u' is not defined

In [ ]:
geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [ ]:
data=pd.concat([data.drop('Geography',axis=1),geo_df],axis=1)

In [ ]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [ ]:
#save one hot encoding and label encoding
with open('Label_Encoder_gender.pkl','wb')as file:
    pickle.dump(Label_Encoder_gender,file)

In [ ]:
with open('one_hot_encoder_geography.pkl','wb')as file:
    pickle.dump(one_hot_encoder_geography,file)

In [ ]:
x=data.drop('Exited',axis=1)
y=data['Exited']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
ss=StandardScaler()
x_train_scaled=ss.fit_transform(x_train)
x_train_scaled=ss.transform(x_test)

In [ ]:
x_train_scaled

array([[-1.13684199, -1.09738852, -1.0465518 , ..., -1.00133422,
        -0.58556189,  1.76021608],
       [-0.11729008,  0.91125429,  1.0305643 , ..., -1.00133422,
         1.70776143, -0.56811207],
       [ 0.43410023, -1.09738852,  1.97470798, ...,  0.99866755,
        -0.58556189, -0.56811207],
       ...,
       [ 0.64217205, -1.09738852, -0.66889433, ...,  0.99866755,
        -0.58556189, -0.56811207],
       [ 1.51607368,  0.91125429, -0.95213743, ..., -1.00133422,
        -0.58556189,  1.76021608],
       [-1.38652817, -1.09738852, -1.14096617, ..., -1.00133422,
        -0.58556189,  1.76021608]], shape=(7000, 12))

In [ ]:
with open('ss.pkl','wb')as file:
     pickle.dump(ss,file)

In [ ]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

ANN IMPLEMENTATION

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
# Build  our ANN model
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),##HL1 connected input
    Dense(32,activation='relu'),##HL2
    Dense(1,activation='sigmoid')##output layer
]
)

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [ ]:
## compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [ ]:
## set up early stopping
Early_Stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [262]:
###train the model
history=model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,
    callbacks=[Early_Stopping_callback]
)

Epoch 1/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7963 - loss: 0.5058 - val_accuracy: 0.7963 - val_loss: 0.5056
Epoch 2/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5056
Epoch 3/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 4/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7963 - loss: 0.5056 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 5/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7963 - loss: 0.5056 - val_accuracy: 0.7963 - val_loss: 0.5056
Epoch 6/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7963 - loss: 0.5060 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 7/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7963 - loss: 0.5059 - val_accuracy: 0.7963 - val_loss: 0.5056
Epoch 8/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7963 - loss: 0.5056 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 9/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 10/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7963 - loss: 0.5059 - val_accuracy: 0.7963 - val_loss: 0.5056
Epoch 11/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7963 - loss: 0.5059 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 12/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7963 - loss: 0.5056 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 13/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5056
Epoch 14/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 15/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7963 - loss: 0.5056 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 16/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 17/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 18/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7963 - loss: 0.5056 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 19/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7963 - loss: 0.5058 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 20/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 21/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.5056 - val_accuracy: 0.7963 - val_loss: 0.5056
Epoch 22/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7963 - loss: 0.5055 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 23/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.5059 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 24/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.5058 - val_accuracy: 0.7963 - val_loss: 0.5057
Epoch 25/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7963 - loss: 0.5058 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 26/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7963 - loss: 0.5059 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 27/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5056
Epoch 28/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 29/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5056
Epoch 30/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5056
Epoch 31/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5055
Epoch 32/100
94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.5057 - val_accuracy: 0.7963 - val_loss: 0.5055

In [266]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.